/**
 * PNG Metadata Extraction Utility
 * Extracts A1111 generation parameters from PNG tEXt chunks
 * Uses native browser APIs - no external dependencies
 */

/**
 * Extract PNG metadata from A1111 images
 * A1111 stores parameters in the tEXt chunk with key "parameters"
 * @param {File} file - PNG file object
 * @returns {Promise<string>} - Parameters text
 */
export async function extractPNGMetadata(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (e) => {
      try {
        const arrayBuffer = e.target.result;
        const view = new DataView(arrayBuffer);

        // Validate PNG signature: 89 50 4E 47 0D 0A 1A 0A
        if (view.byteLength < 8 || view.getUint32(0) !== 0x89504E47) {
          reject(new Error('Not a valid PNG file'));
          return;
        }

        let offset = 8; // Skip PNG signature

        while (offset < view.byteLength) {
          // Check if we have enough bytes for chunk header
          if (offset + 12 > view.byteLength) break;

          const chunkLength = view.getUint32(offset);
          const chunkType = String.fromCharCode(
            view.getUint8(offset + 4),
            view.getUint8(offset + 5),
            view.getUint8(offset + 6),
            view.getUint8(offset + 7)
          );

          // Look for tEXt chunk
          if (chunkType === 'tEXt') {
            // Ensure we have enough bytes for the chunk data
            if (offset + 8 + chunkLength > view.byteLength) break;

            const chunkData = new Uint8Array(arrayBuffer, offset + 8, chunkLength);
            const text = new TextDecoder('utf-8').decode(chunkData);

            // Check if this is the "parameters" key
            // tEXt format: keyword\0text
            if (text.startsWith('parameters\0')) {
              const params = text.substring(11); // Skip "parameters\0"
              resolve(params);
              return;
            }
          }

          // Move to next chunk: 4 (length) + 4 (type) + data + 4 (CRC)
          offset += 12 + chunkLength;
        }

        reject(new Error('No A1111 metadata found in PNG. This image may not have been generated by Automatic1111.'));
      } catch (error) {
        reject(new Error(`Failed to parse PNG: ${error.message}`));
      }
    };

    reader.onerror = () => reject(new Error('Failed to read file'));
    reader.readAsArrayBuffer(file);
  });
}
